name:                quickcheck-scoped
version:             0.1.0.0
github:              "agustinmista/quickcheck-scoped"
license:             BSD3
license-file:        LICENSE
author:              "Agustín Mista"
maintainer:          "Agustín Mista"
copyright:           "2018 Agustín Mista"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            QuickCheck combinators for random generation of scope-sensitive data types.  
category:            Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at <https://github.com/agustinmista/quickcheck-scoped#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: 
    - src
  exposed-modules:
    - Test.QuickCheck.Scoped.Gen
    - Test.QuickCheck.Scoped.Arbitrary
  dependencies:
    - containers
    - transformers
    - mtl
    - QuickCheck
    - QuickCheck-GenT

